### ISSUE TITLE
Timeout occured - NullPointerException

### ISSUE THREAD

**Issue by Haeusele** [worldpeace-germany/rctDataServer#3]
Hi

I tried to use the jar-File. But the console shows:

2021-10-29 19:49:25 | INFO  | [main] application.Inverter (Inverter.java:37) - <<<<< INFO >>>>> Inverter::connect Connected successfully to inverter.
2021-10-29 19:49:25 | INFO  | [main] application.Application (Application.java:64) - <<<<< INFO >>>>> Application::Main: Polling data in regular intervalls to write data to database.
Exception in thread "TCPConnectionThreadRctInverter" java.lang.NullPointerException
        at com.opensource.rct.application.Inverter.processResultString(Inverter.java:432)
        at com.opensource.rct.application.Inverter$1.run(Inverter.java:83)
        at java.lang.Thread.run(Unknown Source)
2021-10-29 19:49:28 | WARN  | [Timer-0] timertasks.PollData (PollData.java:119) - <<<<< WARN >>>>> PollData::getRctData 1AC87AA0 timeout 3048
2021-10-29 19:49:31 | WARN  | [Timer-0] timertasks.PollData (PollData.java:119) - <<<<< WARN >>>>> PollData::getRctData 91617C58 timeout 3057

IP and Port are correct.

Best regards

**Comment by worldpeace-germany** [comment]
Hello,

that part of the code is executed when an unknown key (=magic number) is being sent from the inverter. So the connection to the inverter is working fine, no IP/Port issue. Can you do me a favor please, and set the logLevel in the config file to debug and run the code again. The error above will be the same I assume, but I would like to get the log file please.

Thanks for reporting the issue and helping to improve the code.

**Comment by Haeusele** [comment]
Hi

thank you for quick response and developing this tool ! :)

2021-10-29 22:35:55 | DEBUG | [Timer-0] application.Helper (Helper.java:115) - <<<<< DEBUG >>>>> RequestData::buildRequestByteArrayDataLoggerShort request string is: 2B0104F0BE6429CAA0
2021-10-29 22:35:55 | DEBUG | [Timer-0] timertasks.PollData (PollData.java:69) - <<<<< DEBUG >>>>> PollData::sendRequestToInverter Data has been requested from inverter.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter$1 (Inverter.java:52) - <<<<< DEBUG >>>>> Inverter::tcpConnectionThread Receiving data on TCP socket. Size received: 679
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter$1 (Inverter.java:71) - <<<<< DEBUG >>>>> Inverter::tcpConnectionThread raw string received: 002B0508F0BE642948D1E2B766A1002B05147924ABD930303635423430323039353000000000DD29002B05084BC0F974463900000333002B050871E10B51C099F07CD8FC002B05086E1C5B78C09BE891E17D002B0508B9928C51C09D19E6D9EC002B050824150B8500000000F24A002B0508DB2D2D69AEC16979781182002B050821961B583BA3D70B2E72002B05080AFDD6CFBA4D95B2874D002B0508C0DF2978000000219C62002B05084F735D1041BA412AD909002B0508DF0A735C41B4CCF5D52E002B05081E5FCA7041B07B13FCFF002B0508381B8BF93F8000006D11002B05085570401B48A1931C704E002B0508A9033880489DC8334530002B050865EED11B43BB00212367002B051C16A1F8443031383041373134303130373638000000000000000000008778002B0508400F015B3DDB635BFF0F002B0508959930BF3D89AF8F8CBB002B0508902AFAFB41BFAAABAFFE002B0508B298395D43069081BCE6002B05085BB8075A4313F03DF635002B0508DB11855B000000044B8E002B05080CB5D21B000000041707002B0508A59C842800000000D210002B05087F813D7300000000E27B002B0508F473BC5E000000003E60002B050844D4C533C7175B119881002B050862FBE7DC47AE0A25918F002B05081AC87AA04524D05ACC7B002B0508EFF4B537490FF03BBBA7002B050889EE3EB53D8407334B41002B0508650C1ED73D94B98A720B002B050892BC682D2B3D88C2B9927B002B0508CF053085435D9970BAB2002B050854B4684E435EA9DF5C6C002B05082545E22D2D435DB923EDD6002B050891617C584525BE82EC6C002B05081C4A665F4247E97DB4FC002B0508FC724A9E48784455E690002B050868EEFD3D489EABD1D36B002B0508B1EF67CE4903A44C9332002B0508E9BBF6E441B6A3200CB2002B0508F79D41D941BBB8ACB361
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:204) - <<<<< DEBUG >>>>> Inverter::split2B raw string split into substrings, amount of substrings 46
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:304) - <<<<< DEBUG >>>>> Inverter::cleanResultArray Length of data frame doesn't fit to expected length. Ignoring frame.
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:324) - <<<<< DEBUG >>>>> Inverter::cleanResultArray array to be further processed is of size 1
2021-10-29 22:35:55 | DEBUG | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:429) - <<<<< DEBUG >>>>> Inverter::processResultString string contains unknown magic number (not listed in CSV): F79D41D9
Exception in thread "TCPConnectionThreadRctInverter" java.lang.NullPointerException
        at com.opensource.rct.application.Inverter.processResultString(Inverter.java:432)
        at com.opensource.rct.application.Inverter$1.run(Inverter.java:83)
        at java.lang.Thread.run(Unknown Source)

I hope this helps. If you need more details, don't hesitate to ask.


Thanks !

**Comment by worldpeace-germany** [comment]
Thanks for the answer.

**Short answer:**
in the release folder there is a new version 0.1.3 that should fix the issue for you. Please test and let me know.

**Favor:**
If you want to do me a favor 
a) What software version of the inverter are you using?
b) In the log file check for entries like

WARN  | 2021-10-30 07:36:36 | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:429) - <<<<< DEBUG >>>>> Inverter::processResultString string contains unknown magic number (not listed 
in CSV): F79D41D9

so something say "contains unknown magic number" If you see these lines please send them across.

**Long answer:**
The inverter sends its data with kind of cryptic keys called magic numbers. They are not too well documented, so I might not know all of them. I found that specific magic number luckily so I was able to add it and it is known now. At the same time I found a bug in my code that that unknown magic numbers are handled correctly. At least I hope, testing can only be done with some "tricks". I only request for magic numbers in my code I am aware of, but others can request other magic numbers and the way the inverter is built all the data request from one service is sent to _all_ connected services. So you must have used some tool (mobile app?) which has been asking for this magic number. Btw, the magic number in question was for the heat sink temperature.

**Comment by Haeusele** [comment]
Thanks for the quick fix. It works very well now :)

Version: 2.3.5556

While I'm using iobroker with this adapter, it may comes to this "packages"
https://github.com/lauff/ioBroker.rct

I found the following two lines in the log file. I hope this helps.

DEBUG | 2021-10-29 22:35:55 | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:429) - <<<<< DEBUG >>>>> Inverter::processResultString string contains unknown magic number (not listed in CSV): F79D41D9

WARN  | 2021-10-30 12:23:46 | [TCPConnectionThreadRctInverter] application.Inverter (Inverter.java:429) - <<<<< DEBUG >>>>> Inverter::processResultString string contains unknown magic number (not listed in CSV): B84A38AB


Best regrads

**Comment by worldpeace-germany** [comment]
Thanks. For future issue just open the next ticket or if you see missing features you might now feel free to ping me.
